(function(){
const S={
air:{c:'#F0562B',img:'air.jpg',h:'Air freight: the fastest way between two cities',p:'Your cargo flies on scheduled cargo planes between the major airports we serve. Best when time matters more than cost.',f:[['Typical transit','1 to 4 days'],['Best for','Urgent, fragile, high value'],['Pricing','Per kg']],g:['Electronics and spare parts','Perishables and medical samples','Documents and urgent orders'],s:['We collect from your door or you drop off at our hub.','Cargo is screened and loaded on the next flight.','We clear customs and deliver to the receiver.']},
sea:{c:'#0E7C86',img:'sea.jpg',h:'Sea freight: the lowest cost for heavy cargo',p:'Pallets, part-loads and full containers travel on container ships between ports on every continent we serve.',f:[['Typical transit','14 to 40 days'],['Best for','Heavy, bulky, not urgent'],['Pricing','Per kg, per lane']],g:['Full 20ft and 40ft containers','Machinery, textiles and building materials','Large orders shipped on a schedule'],s:['Cargo is packed and sealed in a container.','The container is loaded on a vessel at the origin port.','We handle customs at the destination port and deliver.']},
road:{c:'#B98700',img:'road.jpg',h:'Road freight: door to door by truck',p:'Trucks move your goods within a landmass and cover the first and last mile for every sea and air shipment.',f:[['Typical transit','1 to 9 days'],['Best for','Regional, pallets'],['Pricing','Per kg']],g:['Pallets and part-loads','Regional deliveries by truck','Pickup and delivery to and from ports and airports'],s:['A truck collects from your address.','Goods travel by road with logged checkpoints.','The receiver signs for delivery.']}};
const m=document.body.dataset.mode,d=S[m],L=window.LGT;
document.getElementById('svc').innerHTML=`
<section class="ph relative mx-5 mx-auto max-w-7xl overflow-hidden rounded-3xl" style="--c:${d.c}"><img src="images/${d.img}" alt="${m} freight" class="absolute inset-0 h-full w-full object-cover" onerror="this.remove()"><div class="absolute inset-0 bg-gradient-to-r from-ink/90 to-ink/20"></div>
<div class="relative p-8 text-white sm:p-14 sm:pt-28"><span class="mb-3 block h-1 w-14 rounded" style="background:${d.c}"></span><h1 class="max-w-2xl text-4xl font-extrabold leading-tight sm:text-6xl">${d.h}</h1><p class="mt-4 max-w-xl text-lg text-white/85">${d.p}</p>
<a href="book.html#quote" class="btn mt-6 !text-white" style="background:${d.c}">Get a ${m} quote</a></div></section>
<section class="mx-auto max-w-7xl px-5 py-12"><dl class="grid gap-6 border-y border-ink/15 py-6 sm:grid-cols-3">${d.f.map(x=>`<div><dt class="text-sm text-ink/60">${x[0]}</dt><dd class="text-xl font-extrabold">${x[1]}</dd></div>`).join('')}</dl>
<div class="mt-10 grid gap-10 md:grid-cols-2"><div><h2 class="text-2xl font-extrabold">What we move</h2><ul class="mt-3 space-y-2 text-ink/80">${d.g.map(x=>`<li class="lane py-1" style="--c:${d.c}">${x}</li>`).join('')}</ul></div>
<div><h2 class="text-2xl font-extrabold">How it works</h2><ol class="tl mt-4" style="--c:${d.c}">${d.s.map(x=>`<li><span class="dot"></span><p>${x}</p></li>`).join('')}</ol></div></div>
<div class="mt-12 flex flex-wrap gap-3 text-sm"><span class="text-ink/60">Other services:</span>${['air','sea','road'].filter(x=>x!==m).map(x=>`<a class="underline" href="${x}.html">${L.MODES[x].label}</a>`).join('')}</div></section>`;
})();
